<?php

namespace Lexik\TestBundle\Repository;

/**
 * Group_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Group_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
