<?php

namespace Lexik\TestBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getClientSearch($clientSearch)
    {  
        $qb = $this
            ->createQueryBuilder('u')
            ->innerJoin('u.group', 'g')
            ->addSelect('g')
            ->where('g.name = :name')
            ->orWhere('u.surname = :name')
            ->setParameter(':name', $clientSearch)
            ->orderby('g.name')
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    public function myFindAll()
    {  
        $qb = $this
            ->createQueryBuilder('u')
            ->innerJoin('u.group', 'g')
            ->addSelect('g')
            ->orderby('g.name')
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
